# Generated by Django 4.1.5 on 2023-02-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user_id',
            field=models.CharField(max_length=200),
        ),
    ]
