# Generated by Django 4.1.5 on 2023-02-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_roommember'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('channel_id', models.CharField(max_length=200)),
            ],
        ),
    ]
