# Generated by Django 4.1.5 on 2023-02-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_onlinemember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinemember',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='roommember',
            old_name='user',
            new_name='user_id',
        ),
    ]
